### ISSUE TITLE
RelatorioView<Usuario> mostra informações erradas

### ISSUE THREAD

**Issue by xvitxr7** [Os-Derivados/college-management#14]
Em [Usuario.cs:49](https://github.com/Os-Derivados/college-management/blob/93a126d359d7d5040eaac1934e2887b6f9df4087/college-management/Dados/Modelos/Usuario.cs#L49C1-L53C3), a função `Usuario.ToString()` retorna uma string que quando usada por `RelatorioView<Usuario>`, na função [`ConstruirLayout()`](https://github.com/Os-Derivados/college-management/blob/93a126d359d7d5040eaac1934e2887b6f9df4087/college-management/Views/RelatorioView.cs#L19), acaba fazendo a _View_ mostrar a suposta "senha" ("x") no lugar do `CargoId` e vice-versa.
![image](https://github.com/user-attachments/assets/9052c886-466b-43c1-be49-00186613cbdd)

# Fix

Simplesmente trocar a ordem da interpolação.
```c#
public override string ToString()
{
return
	$"| {Login,-16} | {Nome,-16} | {"x",-16} | {CargoId,-16} | {Id,-16} |";
//                                     ~~~~~~~~~~~~~~~~~~~~~~~~~
}
```

ou podemos trocar a ordem dos campos do modelo `Usuario`, fazendo `typeof(Usuario).GetProperties()` retornar as propriedades na ordem certa.

```c#
public string? Login   { get; set; }
public string? Nome    { get; set; }
public string  CargoId { get; set; }
public string? Senha   { get; set; }
```

Peço perdão caso isso seja redundante ou diretamente só incorreto, é o meu primeiro issue. 😅

**Comment by trsaints** [comment]
Abri uma branch `fix/14-ordem-relatorio` para tratar disso.

**Comment by xvitxr7** [comment]
Eu entendi que realmente, o ideal não é mostrar a senha dos usuários no relatório. Uma rotina de criptografia para as senhas é uma ótima ideia, se não necessária.
Vou estar corrigindo e dando uma olhada melhor nisso na branch.

**Comment by xvitxr7** [comment]
Estou sem permissões por enquanto, mas sei que ainda está cuidando disso. Estarei esperando!
