### ISSUE TITLE
Desenvolver Contexto de Materias

### ISSUE THREAD

**Issue by trsaints** [Os-Derivados/college-management#17]

**Comment by MarcosMCM21** [comment]
Vou começar a trabalhar nessa Issue, mas só vou começar a fazer isso dia 16/12 à noite, além disso vou postar qual método estou trabalhando ou quando terminar algum

**Comment by MarcosMCM21** [comment]
Desenvolvido os métodos para visualizar e cadastrar uma matéria, utilizei como base os métodos do Contexto de Usuários
