### ISSUE TITLE
Visualizar detalhes de um modelo com propriedades vazias está quebrado

### ISSUE THREAD

**Issue by xvitxr7** [Os-Derivados/college-management#27]
Em [UtilitarioTipos.cs:31](https://github.com/Os-Derivados/college-management/blob/dc3dca8086aa3363936af48f2b943b7cd9f39481/college-management/Utilitarios/UtilitarioTipos.cs#L31), a obtenção do ``valor`` de ``propriedade`` pode retornar um valor nulo, fazendo o resto da lógica falhar e crashar a aplicação.
![image](https://github.com/user-attachments/assets/cc8d288c-e751-406a-8dbc-aee5f61fd83b)
Evidentemente, isso acontece ao tentar visualizar detalhes do usuário ``master.admin`` (Administrador padrão), que tem a propriedade "Nome" vazia. Mas também pode acontecer com qualquer modelo.

**Comment by trsaints** [comment]
Apesar do null check ser relevante, a proposta é que o fluxo de interação não permita o cadastro de informações vazias. Talvez devêssemos criar algum atributo que sinalize o preenchimento dessas informações (com *annotations* mesmo)

**Comment by xvitxr7** [comment]
Acho a proposta interessante, é um bom modo de enforçar campos obrigatórios, embora eu tenha que estudar annotations de uma forma mais detalhada. Apesar disso, eu apoio a ideia dos atributos.
