### ISSUE TITLE
Comando do README para criar o arquivo .env no windows está incorreto

### ISSUE THREAD

**Issue by MarcosMCM21** [Os-Derivados/college-management#31]
Ao tentar criar o arquivo .env utilizando o comando do README apresenta o seguinte erro.
![image](https://github.com/user-attachments/assets/019b97c3-e657-48f5-97bd-3134cf845abd)

Comando correto para criar o arquivo.
![image](https://github.com/user-attachments/assets/d5a837a2-2485-4253-a9e1-931c546cf18f)

**Comment by xvitxr7** [comment]
Fix foi aceita. PR #32
