### ISSUE TITLE
Problemas com autenticação do usuário master.admin e usuario.teste

### ISSUE THREAD

**Issue by MarcosMCM21** [Os-Derivados/college-management#35]
Ao tentar fazer login como admin ou usuário teste apresenta o seguinte erro.
![image](https://github.com/user-attachments/assets/11c1729b-b71d-4dab-9c47-02b2109b0d91)

Eu não descobri a raiz do problema mas pelo o que percebi o hash que ele gera da senha através do arquivo .env e salva no arquivo Usuarios.json na pasta Dados é diferente do que ele gera ao digitar a senha para fazer a comparação.

Teste realizado com o usuário master.admin
![image](https://github.com/user-attachments/assets/e0a3702b-ff73-4b14-9d2b-e8899eb22460)

Senha Digitada:
![image](https://github.com/user-attachments/assets/22cdabaa-05e4-4f42-a73e-16d7f0e34222)

Senha do .env que ele utilizou para criar:
![image](https://github.com/user-attachments/assets/1f5b5f8c-e5d2-4982-9926-47b6ce3390b7)

**Comment by trsaints** [comment]
O @xvitxr7 vai saber responder melhor, mas acredito que um hash esteja sendo gerado durante o login, o que (provavelmente?) não deveria acontecer.

É importante fazer a limpeza total dos dados também, caso tenham feito o pull recentemente.

Talvez deveríamos colocar algum aviso de que a implementação de criptografia é uma "breaking change".

**Comment by MarcosMCM21** [comment]
Pelo o que eu entendo de senha você gera o hash + salt pela primeira vez e armazena, quando o usuário for fazer login você vai geral novamente o hash + salt e verificar com o valor armazenado.

Mas acho que possivelmente descobri o que está causando isso:
![image](https://github.com/user-attachments/assets/44f7fd6e-8129-4ee8-a823-af57b63dfa48)
![image](https://github.com/user-attachments/assets/b8c0a17f-b148-431d-91f7-66f566cab552)

Na hora de gerar o hash ele está pegando o "sal" do parâmetro ao invés de pegar o "Sal" que ele armazenou

**Comment by trsaints** [comment]
Precisamos verificar nos três trechos que um novo usuário é criado ou instanciado: `ContextoUsuarios`, `UtilitarioSeed` e `RepositorioUsuarios`

**Comment by xvitxr7** [comment]
> Na hora de gerar o hash ele está pegando o "sal" do parâmetro ao invés de pegar o "Sal" que ele gerou e armazenou

O problema é esse mesmo. Testando agora e funcionando perfeitamente. Foi um erro bobo na hora de escrever "Sal", e descuidado meu ao não testar a alteração apropriadamente, peço perdão.

**Comment by xvitxr7** [comment]
> Precisamos verificar nos três trechos que um novo usuário é criado ou instanciado: `ContextoUsuarios`, `UtilitarioSeed` e `RepositorioUsuarios`
De fato, essas outras áreas podem apresentar defeitos também.
