### ISSUE TITLE
Autenticação inválida termina a aplicação, esse comportamento é por design?

### ISSUE THREAD

**Issue by xvitxr7** [Os-Derivados/college-management#40]
Como o título é bem autoexplicativo, serei breve. Ao inserir credenciais inválidas na etapa de login, o programa tenta progredir com o fluxo normalmente, mesmo com o usuário logado sendo inválido.

Isso é por design ou um oversight?

**Comment by trsaints** [comment]
Na verdade, a proposta era que todos os processos interativos rodassem em loop, em caso de falha ou invalidação das informações captadas.

Essa implementação atual foi meramente a nível de funcionalidade mínima. O login, em específico, foi implementado pelo @CharlesSanto

**Comment by xvitxr7** [comment]
Entendi. Os loops teriam que rodar de um modo global ou é um requesito comum entre eles?

**Comment by trsaints** [comment]
A proposta é que todo o ciclo de cada funcionalidade esteja rodando em um loop onde o usuário, voluntariamente, deseje sair daquele recurso, voltar para um menu anterior, etc.

Estou a encargo de fazer alguns ajustes iniciais, conforme listado em #41

**Comment by xvitxr7** [comment]
> A proposta é que todo o ciclo de cada funcionalidade esteja rodando em um loop onde o usuário, voluntariamente, deseje sair daquele recurso, voltar para um menu anterior, etc.
> 
> Estou a encargo de fazer alguns ajustes iniciais, conforme listado em #41

Vi lá agora, saquei saquei. Até percebi que tem um ``EstadoDoApp.Login`` que não é usado em lugar nenhum; assumo que está de olho e trabalhando em cima 👀. Bom, estarei pacientemente esperando as mudanças, estou pronto para fazer a review da PR quando terminar!
