### ISSUE TITLE
Seed criando matrículas redundantes

### ISSUE THREAD

**Issue by xvitxr7** [Os-Derivados/college-management#47]
Ao inicializar o projeto com o Modo Seed ativado, matrículas são criadas para alunos, independente se eles já possuem uma ou não, eliminado a idempotência do Seed.

### Possíveis causas

- Falha na checagem de existência matrículas iguais na base de dados.
- Falha na contagem de Id.

**Comment by Sutolix** [comment]
Parece que isso ocorre porque mesmo que a criação do usário falhe o utilitário continua com a criação da matricula como percebe-se aqui:
https://github.com/Os-Derivados/college-management/blob/main/college-management/Utilitarios/UtilitarioSeed.cs#L62

Vou abrir uma PR com uma verificação
